#index:
#    path: /
#    controller: App\Controller\DefaultController::index

captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
recherche:
  path: /recherche
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\ReclamationController::Rec
