Achat:
    type: entity
    table: achat
    indexes:
        id_fk:
            columns:
                - id
        id_user_fk:
            columns:
                - id_user
    id:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_user
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    lifecycleCallbacks: {  }
