DoctrineMigrationVersions:
    type: entity
    table: doctrine_migration_versions
    id:
        version:
            type: string
            nullable: false
            length: 191
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        executedAt:
            type: datetime
            nullable: true
            options:
                default: 'NULL'
            column: executed_at
        executionTime:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
            column: execution_time
    lifecycleCallbacks: {  }
