Formation:
    type: entity
    table: formation
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
        difficulte:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        cours:
            type: blob
            nullable: true
            length: 0
            options:
                fixed: false
                default: 'NULL'
        certificat:
            type: boolean
            nullable: true
        image:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: Image
    lifecycleCallbacks: {  }
