Publicite:
    type: entity
    table: publicite
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        domaine:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        affichage:
            type: string
            nullable: false
            length: 130
            options:
                fixed: false
            column: Affichage
        image:
            type: blob
            nullable: true
            length: 0
            options:
                fixed: false
                default: 'NULL'
        prix:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
            column: Prix
        lien:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
                default: 'NULL'
    lifecycleCallbacks: {  }
