Questionn:
    type: entity
    table: questionn
    indexes:
        idQuiz:
            columns:
                - idQuiz
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        question:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        option1:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        option2:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        option3:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        option4:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        reponse:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        idquiz:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: idQuiz
    lifecycleCallbacks: {  }
