Recformation:
    type: entity
    table: recformation
    id:
        idFormation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_formation
            generator:
                strategy: IDENTITY
    fields:
        formation:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        nomFormateur:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nom_formateur
        description:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
