Reclamation:
    type: entity
    table: reclamation
    id:
        idReclamation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_reclamation
            generator:
                strategy: IDENTITY
    fields:
        examen:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        date:
            type: date
            nullable: false
        nomFormateur:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nom_formateur
        description:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
